// This file was automatically generated by ts_bind, do not modify it manually
import type { ObjectId } from "./ObjectId";
import type { DateTime } from "./DateTime";

export interface Merchant {
   id: ObjectId;
   name: string;
   description: string;
   location: string;
   createdAt: DateTime | null;
   createdBy: ObjectId | null;
   updatedAt: DateTime | null;
   updatedBy: ObjectId | null;
   isDeleted: boolean | null;
   deletedAt: DateTime | null;
   deletedBy: ObjectId | null;
}