// This file was automatically generated by ts_bind, do not modify it manually
import type { ObjectId } from "./ObjectId";

export interface Product {
   id: ObjectId;
   name: string;
   description: string;
   price: number;
   quantity: number;
}