// This file was automatically generated by ts_bind, do not modify it manually
import type { ObjectId } from "./ObjectId";

export interface User {
   id: ObjectId;
   username: string;
   password: string;
   email: string;
   birthday: string;
}